// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_file_ from "./routes/[id]/[file].ts";
import * as $_id_index from "./routes/[id]/index.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $gfm_css from "./routes/gfm.css.ts";
import * as $index from "./routes/index.tsx";
import * as $CopyButton from "./islands/CopyButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id]/[file].ts": $_id_file_,
    "./routes/[id]/index.tsx": $_id_index,
    "./routes/_app.tsx": $_app,
    "./routes/gfm.css.ts": $gfm_css,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CopyButton.tsx": $CopyButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
