export const TOC = [
  "hello-world",
  "color-logging",
  "import-export",
  "dependency-management",
  "timers",
  "prompts",
  "environment-variables",
  "reading-files",
  "writing-files",
  "moving-renaming-files",
  "http-requests",
  "uuids",
  "http-server",
  "http-server-routing",
  "http-server-streaming",
];
