// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/_render.ts";
import * as $2 from "./routes/gfm.css.ts";
import * as $3 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/_render.ts": $1,
    "./routes/gfm.css.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
