// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/_render.ts";
import * as $1 from "./pages/[id].tsx";
import * as $2 from "./pages/gfm.css.ts";
import * as $3 from "./pages/index.tsx";

const routes = {
  pages: {
    "./pages/_render.ts": $0,
    "./pages/[id].tsx": $1,
    "./pages/gfm.css.ts": $2,
    "./pages/index.tsx": $3,
  },
  baseUrl: import.meta.url,
};

export default routes;
